#!/usr/bin/env bash

#*****************************************************************************************
# Author    : Gheevarghese (George) Muthalaly
# Created   : June 02, 2019
# Purpose   : Load data into the table current_s3_file_list from current_s3_file_list.txt.
#           : current_s3_file_list.txt is a list of files in the S3 bucket - generated by 
#           : the caller of this script.
#           : File names in current_s3_file_list table minus file names in ndvr_job_status
#           : table generates the files that are not referred by a job and needs to be deleted.
#           : The caller of this script deletes the files.
#
# Modification History
# Date                 Name                      Description
#
#*****************************************************************************************

# See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.html
# for more details on connecting to RDS with IAM credentials.

RDSHOST='dataops.cnh8zrq6tuc4.us-east-1.rds.amazonaws.com'
USERNAME='dataops'
DATABASE='homework'

TOKEN="$(aws --profile homework \
			 rds generate-db-auth-token \
			 --hostname ${RDSHOST} \
			 --port 3306 \
			 --region us-east-1 \
			 --username ${USERNAME})"

# The `rds-combined-ca-bundle.pem` file must be in the same folder as this
# script.
mysql --host="${RDSHOST}" \
	  --port=3306 \
	  --ssl-ca=rds-combined-ca-bundle.pem \
	  --enable-cleartext-plugin \
	  --user="${USERNAME}" \
	  --password="${TOKEN}" \
	  "${DATABASE}"   <<EOFMYSQL

###################################
# Delete any existing data in the table current_s3_file_list
###################################

delete from current_s3_file_list;

###################################
# Load data into the table current_s3_file_list from current_s3_file_list.txt
###################################

LOAD DATA LOCAL INFILE './current_s3_file_list.txt' 
INTO TABLE current_s3_file_list LINES TERMINATED BY '\n'
(sourceData);

EOFMYSQL